const logo = document.querySelector(".logo-text");
const changedLogo = (logo.style.color = "#384241");
console.log(changedLogo);
let header = document.querySelector("header");
header.style.justifyContent = "flex-start";
header.style.borderBottom = "1px solid lightgray";
console.log(header.style.justifyContent);
let name = (document.getElementById("recipe-name").textContent = "Frozen Cheescake");
let icon1 = document.querySelector(".time-container span");
icon1.classList.add("material-icons");
const recipeTime = document.querySelector(".time");
recipeTime.innerText = "60+ min";
const image = document.querySelector(".image-container");
const img = image.firstElementChild;
img.setAttribute("src", "assets/frozen-cheesecake-slice.jpg");
console.log(img.getAttribute("src"));
const bgColor = document.querySelector(".ingredients-container");
const background = (bgColor.style.backgroundColor = "#f9f9f9");
console.log(background);
const listItems = document.querySelector(".ingredients-list-bottom");
listItems.innerHTML = " <li>15st digistivetex</li><li>Lite smör</li>";
const listPaste = document.querySelectorAll(".ingredients-list-paste li");
listPaste[2].textContent = "3tsk vaniljsocker";
const pasteList = document.querySelector(".ingredients-list-paste");
pasteList.insertAdjacentHTML("beforeend", "<li>400g naturell philadelphiaost</li>");
const instruction = document.querySelector(".instructions");
instruction.classList.remove("shadow");
const element = document.querySelector(".instructions-list");
const elements = element.children;
elements[1].textContent =
  "Separera ägggulor och äggvitor. Äggvitorna lägger du i en stor bunke, äggulorna i en liten bunke.";
elements[8].textContent = "Ställ in i frysen över natten.";
